import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Providers } from '@/providers';
import { Sidebar } from '@/components/ui/sidebar';
import MobileSidebar from '@/components/ui/mobileSidebar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='flex items-center gap-2 h-screen font-PlusJakartaSans'>
        <div className=' hidden md:block'>
          <Sidebar />
        </div>
        <div className=' h-screen w-screen py-6 -inset-2 px-5'>
          <div className='flex items-center justify-end sm:hidden '>
            <MobileSidebar />
          </div>
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
